select_period: |
  ๐ ะัะฑะตัะธัะต ะฟะตัะธะพะด ะดะปั ะฐะฝะฐะปะธะทะฐ:
analysis: |
  ๐ <b>ะะฝะฐะปะธะท ะทะฐ {period}</b>
  
  ๐ฐ ะะพัะพะดั: {income} ััะฑ.
  ๐ธ ะะฐััะพะดั: {expenses} ััะฑ.
  
  {analysis}
invalid_period: |
  โ ะะตะฒะตัะฝัะน ะฟะตัะธะพะด
error_occurred: |
  โ๏ธ ะัะพะธะทะพัะปะฐ ะพัะธะฑะบะฐ, ะฟะพะฟัะพะฑัะนัะต ะฟะพะทะถะต.
analysys_emoji: |
  ๐
menu: |
  <b>ะะตะฝั</b>
loading: |
  โณ ะะฝะฐะปะธะทะธััั ะฒะฐัะธ ััะฐะฝะทะฐะบัะธะธ...
  
  ะะพ ะพะบะพะฝัะฐะฝะธะธ ะฒะฐะผ ะฟัะธะดะตั ัะพะพะฑัะตะฝะธะต!